### ISSUE TITLE
Will break very hard when gulp4 is released

### ISSUE THREAD

**Issue by phated** [frankwallis/gulp-hub#15]
This module relies on so many internals of gulp that are changing and will break upon release of gulp4.

This module can actually be replaced with custom registries in gulp4.  Have you considered creating one?

**Comment by frankwallis** [comment]
Thanks for the heads up, and I'm very pleased to hear that there is a more supported way of doing this in gulp4! I'll create a new version shortly...

**Comment by frankwallis** [comment]
created https://github.com/frankwallis/gulp-hub/tree/4.0

**Comment by phated** [comment]
Very cool,  why still export the `hub` method that takes globs?  When creating custom registries, I invisioned something like:

```js
// gulpfile.js
var gulp = require('gulp');
var Hub = require('gulp-hub');

var hub = new Hub(['./project1/gulpfile.js', './project1/gulpfile.js']);
gulp.registry(hub);
```

**Comment by frankwallis** [comment]
Thanks - yes I wasn't quite sure how they were supposed to be used. I like the separation between tasks and dependencies in gulp4, it makes things a lot easier.

I will change it to use the syntax you suggest.

**Comment by phated** [comment]
@frankwallis any more progress on my last comment?  I'd like to make gulp-hub the recommended module for hooking up multiple gulpfiles into a central registry.

We now have documentation on Custom Registries - https://github.com/phated/undertaker#custom-registries

**Comment by frankwallis** [comment]
@phated I've changed the 4.0 branch to use the API you suggested and updated the README. 

It was a bit more complicated than I expected due to the way that gulp-hub needs to load gulpfiles and then return the gulp registry back to it original state. It also doesn't know what instance of gulp the gulpfile is going to use before loading it so it can't just put its own registry in place first.

Gulp-hub creates new wrapper tasks (using gulp.task) for each of the tasks exposed by the gulpfiles so that it can give them unique names to display in the listings and in ```gulp --tasks```. However calling gulp.task also affects the underlying registry so it is difficult for 'detached' registries to create new tasks internally.

I think this is mostly to do with gulp-hub having a slightly strange use-case for custom registries, but I think it is worth it to have a standard API which aligns with other gulp plugins. If you know a better way to achieve what I need then please let me know.

**Comment by phated** [comment]
Couldn't the `set` method be filepath-aware?  I see that invalidateTasks is replacing tasks with new unique names, but I figured `set` could just do that.  Personally, I think that the 4.0 gulp-hub should only work with gulp 4.0.  I could add a `.version` property for you to check

**Comment by frankwallis** [comment]
I agree gulp-hub should only work with 4.0, the issue is that you don't know before loading a gulpfile what *instance* of gulp it is going to use. It may well have its own local gulp installation, in which case the tasks will be loaded into a different instance of gulp from the one that gulp-hub is using. This is why gulp-hub does not attach its registry before loading the files.

I'll have another look at creating the tasks with ```set```. It seemed at the time that the only way to get a taskWrapper was by calling gulp.task, but your examples show the shared 'clean' method using ```set``` so I will have a look at how that works.

**Comment by phated** [comment]
`taskWrapper` is generated through the `set` method of undertaker, which adds the taskWrapper and passes that through to the registry's `set` method. If you modify the taskWrapper in any way, you need to return it so undertaker knows of the new wrapper.  I also wonder if you would be able to use the `description` property (https://github.com/gulpjs/gulp-cli/issues/19) to display the file the task was loaded from.

**Comment by phated** [comment]
I would say that you should be able to run each gulpfile in a separate sandbox and pass in a special `require` method that forces them to use the correct gulp or it fails.

**Comment by frankwallis** [comment]
I like the sandbox idea, I'll give that a try - thanks.

**Comment by frankwallis** [comment]
@phated I have changed it to load gulpfiles using a sandboxed instance of gulp and everything looks a lot cleaner now. I will have a look at the description stuff when I get a bit more time.

**Comment by phated** [comment]
@frankwallis this is really awesome. Going to add a gulp4 recipe to use the 4.0 branch of this

**Comment by frankwallis** [comment]
cool, thanks
